models/order.py
from utils.db import db


class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    order_number = db.Column(db.String(50), unique=True, nullable=False)

    # order_date = db.Column(db.DateTime, nullable=False)

    def __init__(self, order_number):
        self.order_number = order_number
        # self.order_date = order_date

main.py
from flask import Flask
from routes.orders import orders
from flask_sqlalchemy import SQLAlchemy
app = Flask(__name__, static_url_path='/static')
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:1234@localhost:3306/ordersdb'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

SQLAlchemy(app)
app.register_blueprint(orders)

routes/orders.py
from flask import Blueprint, render_template, request, redirect

from models.order import Order
from utils.db import db

orders = Blueprint('orders', __name__)


@orders.route('/')
def hello():
    # orders = Order.query.all()
    page = request.args.get('page', 1, type=int)
    try:
        orders = Order.query.paginate(page=page, per_page=3)
    except:
        orders = Order.query.paginate(page=1, per_page=3)
        return render_template('index.html', orders=orders)

    # if page > orders.pages:
    #     orders = Order.query.paginate(page=1, per_page=3)
    #     return render_template('index.html', orders=orders)

    # if orders is None:
    #     return render_template('orders.html', orders=[])

    for recorrer in orders.items:
        print('numero de orden', recorrer.order_number, 'id', recorrer.id)

    return render_template('index.html', orders=orders)


@orders.route('/new', methods=['POST'])
def add_order():
    order_number = request.form['order_number']
    new_order = Order(order_number)

    db.session.add(new_order)
    db.session.commit()

    return redirect('/')

# @orders.route('/buscar', methods=['GET'])
# def pagina_buscar():
#     return render_template('buscar.html')


# @orders.route('/busqueda', methods=['POST'])
# def buscar():
#     order_number = request.form['order_number']
#     print(order_number)
# consult_orders = Order.query.filter_by(order_number=order_number).first()


# def consult_order(consult_orders):
#     print("print consult_orders", consult_orders)
# return render_template('consult.html', orders=consult_orders)

templates/buscar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Buscar</title>
</head>
<body>
<h1>Buscar</h1>
<div>
    <h2>Buscar</h2>
    <form action="/busqueda" method="POST">
     <input type="text" name="buscar" placeholder="buscar">
     <button type="submit">Buscar</button>
    </form>

</div>
</body>
</html>

templates/consult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Consult</title>
</head>
<body>
<h1>Consult</h1>
<div>

    <h1>Orders</h1>
    <h1>{{orders.order_number}}</h1>

</div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
  <!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.css"
  rel="stylesheet"
/>
      <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-dark bg-primary">
  <a class="navbar-brand" href="?">
      <h5>&nbsp;&nbsp;</h5>
    <img src="../static/img/coding.png" width="30" height="30" class="d-inline-block align-top" alt="">
    Buscador por paginación
  </a>
</nav>

<div class="container">
    <div class="row">
    <div class="col">
  <h1>&nbsp;</h1>
    </div>
    <div class="col">
  <h1>&nbsp;</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-sm">

    </div>
    <div class="col-sm">
      <form action="/new" method="POST">
<!--    <input type="text" name="order_number" placeholder="order number">-->


<!--       <div class="input-group mb-3">-->
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">New order</span>
  </div>
  <input type="text"  name="order_number" class="form-control" placeholder="write here" aria-label="Username" aria-describedby="basic-addon1">
        <button type="submit" class="btn btn-success" name="order_number">Success</button>
<!--</div>-->

</form>

    </div>
    <div class="col-sm">

    </div>
         <div class="col-sm">
      <div>
    <h2>Orders</h2>
   <ul>
        {% if orders.items %}
            {% for order in orders.items %}
                <li>{{ order.order_number }}</li>
            {% endfor %}
           <!--  <a class="btn btn-info mb-4" href="{{ url_for('orders.hello', page=total_pages) }}">{{ actual_page }}</a>
             <a class="btn btn-info mb-4">{{ total_pages }}</a>-->
        {% endif %}
       {% if not orders.items %}
           <li>No orders yet</li>
       {% endif %}

    </ul>


      {% for page_num in orders.iter_pages(left_edge=1, right_edge=1,
    left_current=1, right_current=1) %} {% if page_num %} {% if orders.page ==
    page_num %} <a class="btn btn-info mb-4" href="{{ url_for('orders.hello',
    page=page_num) }}">{{ page_num }}</a> {% else %} <a class="btn btn-info mb-4"
    href="{{ url_for('orders.hello', page=page_num) }}">{{ page_num }}</a> {% endif
    %} {% else %} <a class="btn btn-info mb-4">...</a> {% endif %} {% endfor %}


</div>
    </div>
         <div class="col-sm">

    </div>
  </div>
</div>


<footer class="text-center text-white" style="background-color: #f1f1f1;">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

</body>
</html>